import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';

/// Every sound effect in the game. Names map to `assets/audio/<name>.wav`,
/// all of which are generated by `tool/generate_audio.dart`.
enum Sfx {
  tap,
  wordFound,
  invalid,
  levelComplete,
  coin,
  button,
  hint,
  unlock,
  streak;

  /// enum name -> snake_case file name.
  String get asset {
    final snake = name.replaceAllMapped(
      RegExp('[A-Z]'),
      (m) => '_${m[0]!.toLowerCase()}',
    );
    return 'audio/$snake.wav';
  }
}

/// Plays short sound effects.
///
/// Design notes:
///  * A small **pool** of players is reused so rapid-fire effects (dragging
///    across letters) never allocate a player per tap.
///  * `tap` is throttled — during a fast swipe it can fire 15x/second, which
///    sounds like static without a floor on the interval.
///  * Audio failures are always swallowed. A device with a broken audio route
///    should still be able to play the game silently.
class AudioService {
  AudioService();

  static const _poolSize = 4;

  final List<AudioPlayer> _pool = [];
  int _next = 0;
  bool _initialised = false;

  bool _soundEnabled = true;
  bool _musicEnabled = true;

  DateTime _lastTap = DateTime.fromMillisecondsSinceEpoch(0);
  static const _tapThrottle = Duration(milliseconds: 45);

  /// Creates the player pool. Safe to call more than once.
  Future<void> init() async {
    if (_initialised) return;
    _initialised = true;
    try {
      for (var i = 0; i < _poolSize; i++) {
        final player = AudioPlayer()
          ..setReleaseMode(ReleaseMode.stop)
          // `lowLatency` would be ideal but limits us to preloaded clips on
          // some platforms; `playAndForget` behaviour with a pool is a good
          // balance and works consistently on Android and iOS.
          ..setPlayerMode(PlayerMode.lowLatency);
        await player.setSourceAsset(Sfx.tap.asset);
        _pool.add(player);
      }
    } catch (error) {
      debugPrint('AudioService: init failed ($error) — running silently.');
      _pool.clear();
    }
  }

  void applySettings({required bool sound, required bool music}) {
    _soundEnabled = sound;
    _musicEnabled = music;
  }

  bool get isMusicEnabled => _musicEnabled;

  /// Fire-and-forget playback. Never awaited by callers on the UI path.
  void play(Sfx sfx) {
    if (!_soundEnabled || _pool.isEmpty) return;

    if (sfx == Sfx.tap) {
      final now = DateTime.now();
      if (now.difference(_lastTap) < _tapThrottle) return;
      _lastTap = now;
    }

    unawaited(_playAsset(sfx));
  }

  Future<void> _playAsset(Sfx sfx) async {
    try {
      final player = _pool[_next];
      _next = (_next + 1) % _pool.length;
      await player.stop();
      await player.play(AssetSource(sfx.asset), volume: _volumeFor(sfx));
    } catch (error) {
      // Silent failure by design — see class docs.
      debugPrint('AudioService: could not play ${sfx.name} ($error).');
    }
  }

  /// Per-effect mix levels, so frequent sounds sit under celebratory ones.
  double _volumeFor(Sfx sfx) => switch (sfx) {
        Sfx.tap => 0.35,
        Sfx.button => 0.45,
        Sfx.invalid => 0.55,
        Sfx.wordFound => 0.75,
        Sfx.coin => 0.65,
        Sfx.hint => 0.7,
        Sfx.levelComplete => 0.9,
        Sfx.unlock => 0.85,
        Sfx.streak => 0.8,
      };

  Future<void> dispose() async {
    for (final player in _pool) {
      try {
        await player.dispose();
      } catch (_) {
        // Disposal errors are not actionable.
      }
    }
    _pool.clear();
    _initialised = false;
  }
}

/// Local `unawaited` so we do not pull in `dart:async` at every call site.
void unawaited(Future<void> future) {
  future.catchError((Object _) {});
}
